import { makeStyles } from "tss-react/mui";

export const useStyles = makeStyles<{ markerColor?: string }>()((theme, { markerColor }) => ({
  sectionContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(800px, 1fr))",
    width: "100%",
    gap: "32px",
  },
  section1: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    p: {
      fontFamily: "Open Sans",
      fontSize: "18px",
      fontWeight: 400,
      lineHeight: "28px",
      margin: "12px 0",
    },
    ul: {
      listStyle: "none",
      paddingLeft: "19px",
      margin: "0 0 24px 0",
      fontFamily: "Open Sans",
      fontSize: "18px",
      fontWeight: 400,
      lineHeight: "28px",
      "> li": {
        position: "relative",
        paddingLeft: "20px",
        margin: "16px 0",
        "&::before": {
          content: '""',
          position: "absolute",
          top: "50%",
          left: "-8px",
          width: "12px",
          height: "12px",
          borderRadius: "50%",
          backgroundColor: markerColor,
          transform: "translateY(-50%)",
        },
      },
    },
    a: {
      display: "inline",
      textDecoration: "underline",
      color: markerColor,
      filter: "saturate(500%)",
    },
  },
  section2: {},
  
  formatedText: {
    h2: {
      fontSize: "40px",
      fontWeight: 700,
      lineHeight: "48.76px",
      margin: "0 0 28px 0",
    },
    h3: {
      fontSize: "32px",
      fontWeight: 600,
      lineHeight: "39.01px",
      margin: "32px 0",
    },
    h4: {
      fontSize: "24px",
      fontWeight: 600,
      lineHeight: "29.26px",
      margin: "24px 0 12px 0",
    },
    p: {
      fontFamily: "Open Sans",
      fontSize: "18px",
      fontWeight: 400,
      lineHeight: "28px",
      margin: "12px 0 24px 0",
    },
    ul: {
      listStyle: "none",
      paddingLeft: "19px",
      margin: "0 0 24px 0",
      fontFamily: "Open Sans",
      fontSize: "18px",
      fontWeight: 400,
      lineHeight: "28px",
      "> li": {
        position: "relative",
        paddingLeft: "20px",
        margin: "16px 0",
        "&::before": {
          content: '""',
          position: "absolute",
          top: "50%",
          left: "-8px",
          width: "12px",
          height: "12px",
          borderRadius: "50%",
          backgroundColor: markerColor,
          transform: "translateY(-50%)",
        },
      },
    },
    a: {
      display: "inline",
      textDecoration: "underline",
      color: markerColor,
      filter: "saturate(100%)",
    },
  },
  picture: {
    float: "right",
    margin: "58px 0 20px 40px",
  },
  pictureLeft: {
    float: "left",
    margin: "0px 40px 20px 0",
  },
  button: {
    display: "flex",
    width: "530px",
    height: "87px",
    borderRadius: "100px",
    backgroundColor: "#3798EA",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    marginTop: "12px",
  },
}))